name: toxic-clf

channels:
  - defaults
  
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy=1.17.2 # so we get the mkl libs as well
  - pandas=1.0.1
  - seaborn=0.9.0
  - matplotlib=3.1.3
  - statsmodels=0.10.1
  - scikit-learn=0.21.3
  - nltk=3.4.5

  - pip:
    - pytest==4.6.3
    - pylint==2.3.1
    - gunicorn==20.0.4
    - sqlalchemy==1.3.8
    - tensorflow==2.2.0
    - jupyter_contrib_nbextensions==0.5.1
    - transformers==3.0.2
    - vaderSentiment==3.3.2
    - mlflow==1.17.0
