TRAIN:
  BiLSTMClfTF:
    input_length: 100
    output_dim: 50
    epochs: 3
    validation_split: 0.2
    batch_size: 4
    verbose: 1
    n_words: 10000
  BertSeqClfPT:
    epochs: 2
  BertSeqClf:
    overwrite_output_dir: True
    num_train_epochs: 1
    gradient_accumulation_steps: 16
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    weight_decay: 0.01
    load_best_model_at_end: True
    logging_steps: 200
    evaluation_strategy: epoch
    logging_strategy: epoch
    save_strategy: epoch
    fp16: False
    fp16_opt_level: O1
    report_to: mlflow
    run_name: 1234